### ISSUE TITLE
Bug - incorrect regions validation

### ISSUE THREAD

**Issue by Przemek2907** [dnsimple/dnsimple-java#103]
It is possible for me to add A record using curl, however when using Java client API and specifically running this line:
`dnsClient.zones
                .createZoneRecord(clientId, myDomain, ZoneRecordOptions
                .of("ABC", "A", "1.2.3.4"))`
 I get 400 Http Status. After debugging very deep the client library, I found the following error message:
"Regions are not allowed in Your plan"
I am not setting up any region explicitly - in the debug mode I see that the Java Client placed here "global" as written in the documentation. I think there is a bug in the library as it adds the "global" region, but then it validates the request against the plan and reject it, due to the regions value specified.
When I set the value of regions to null explicitly via Java reflection mechanism, everything works fine

**Comment by ggalmazor** [comment]
Thanks for the bug report, @Przemek2907. We're on it

**Comment by ggalmazor** [comment]
Just FYI, @Przemek2907, you can catch `BadRequestException` (or `DnsimpleException` for any exception originating from this library) to access all the relevant data about any error you get while using it.

**Comment by ggalmazor** [comment]
@Przemek2907, the fix for this issue is in the review process at https://github.com/dnsimple/dnsimple-java/pull/104

If possible, It would be great to have your feedback about it but it's OK if you can't. We will be releasing it shortly anyway. Thanks!

**Comment by Przemek2907** [comment]
@ggalmazor Thanks! It works fine now and I can get rid of my reflection hack

**Comment by ggalmazor** [comment]
I'm glad to hear that! Thanks for your feedback!
