### ISSUE TITLE
Change Certificates

### ISSUE THREAD

**Issue by ecomba** [dnsimple/dnsimple-java#118]
The methods `downloadCertificate` and `getCertificatePrivateKey` both return a `CertificateBundle` object.

The issue here is that if I am downloading and I access the `getPrivateKey` method on the `CertificateBundle`, I'll be greeted with a juicy `Null`.

It would be way better to separate the `CertificateBundle` into (at least) two objects so that there are no surprises for the developer working with our Java client.

Here is a case where this was misused, and worst of all, we show it when we showcase how our Java client works! In our [API showcase](https://dnsimple.com/api), if you click on Java and then SSL Certificates, you will see the last example is wrong and will result in a `Null` being returned and not the desired private key! You can actually see it in the [dnsimple app as well](https://github.com/dnsimple/dnsimple-app/blob/e7b1baa319c1f7c0be6584c3e4bd182d442cc541/app/javascript/components/api-browser/api-browser-data.js#L656-L661)

**Comment by ggalmazor** [comment]
We've added this to the backlog :)

**Comment by DXTimer** [comment]
This has been implemented in #150. Will be shipped as part of v1.
