### ISSUE TITLE
deleteZoneRecord throws exception even when call to API is successful

### ISSUE THREAD

**Issue by bradleydwyer** [dnsimple/dnsimple-java#13]
Using 0.6.0

While invoking com.dnsimple.Zones#deleteZoneRecord against the production API I keep getting an exception even when the underlying HTTP call returns a successful 204 response and the corresponding zone record is deleted (no longer visible in the dnsimple.com UI)

Within com.dnsimple.endpoints.http.HttpEndpointClient#parseResponse an exception is thrown as it attempts to parse JSON from the response body, however there is none present in this call (the API documentation notes it just returns a 204 when successful).

The exception thrown is: java.lang.IllegalArgumentException: no JSON input found

**Comment by jodosha** [comment]
@bradleydwyer Hi, I'm sorry about this problem.

Do you mind to share a code snippet to reproduce it? Thanks in advance!

**Comment by ggalmazor** [comment]
Hi, @bradleydwyer!

Sorry for the delay (1 year already!).

I've been able to reproduce the error with the following snippet:
```java
package com.github.dnsimple.demo;

import com.dnsimple.Client;
import com.dnsimple.exception.DnsimpleException;
import java.io.IOException;

public class ProductionTest {
    public static final String ACCOUNT_ID = "1234";
    public static final String ZONE_NAME = "example.com";

    public static void main(String[] args) throws IOException, DnsimpleException {
        Client client = new Client();
        client.setAccessToken("---- SECRET ----");
        client.setUserAgent("your-user-agent");
        client.zones.deleteZoneRecord(ACCOUNT_ID, ZONE_NAME, "1234");
    }
}
```
