### ISSUE TITLE
How to set access token?

### ISSUE THREAD

**Issue by nmeyvis** [dnsimple/dnsimple-java#3]
How do I set the access token I generated from my account page?

The read me usage does not make any sense.

    Client client = new Client();
    WhoamiResponse response = client.identity.whoami();
    Account account = response.getData().getAccount();
    System.out.println("Account: " + account);

How can you get information about the current authenticated context when no authentication was seemingly done?

**Comment by aeden** [comment]
You are absolutely right, there is a significant piece missing. I'll correct the library and the README and will update this issue when that is done.
