### ISSUE TITLE
Add dependabot badge

### ISSUE THREAD

**Issue by ggalmazor** [dnsimple/dnsimple-java#54]
`@dependabot badge me` https://github.com/dependabot/feedback/issues/6#issuecomment-470600620

**Comment by weppos** [comment]
@dependabot badge me

**Comment by weppos** [comment]
I could not make it to work in other PRs. It doesn't seem to be officially supported.
There's an unofficial integration, but the current state is:

<img width="667" alt="Screenshot 2021-08-06 at 15 16 30" src="https://user-images.githubusercontent.com/5387/128516114-dce04c51-82b1-4393-a8da-f97de20ae6b6.png">
