### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by esfomeado** [dnsimple/dnsimple-java#76]
Hello,

Please publish this library to the maven central repositories to make it easier to include it in the projects.

Thanks

**Comment by ggalmazor** [comment]
Hi there!

We're planning on releasing this during the first half of september. Would you be interested in using it sooner than that? We could consider deploying a release candidate in maven central.

**Comment by esfomeado** [comment]
Yes.

I want to integrate a DNS hosting and domain registration solution on my company's new project as soon as possible and saw this project and seems like a life saver.
If you could please deploy a release candidate in maven central I would be grateful. I will happily test it for you.

Thanks

**Comment by ggalmazor** [comment]
Awesome! I'll do a 0.8.0 release asap and let you know. Stay tuned ;)

**Comment by ggalmazor** [comment]
Hi again!

0.8.0 has been released to Maven Central 🎉 

Happy coding!

**Comment by ggalmazor** [comment]
By the way, feel free to contact again if you need help with anything ;)

**Comment by esfomeado** [comment]
Thanks for your help :)
